version: '2.1'

services:
  app:
    image: maxca789/php56apachecomposer
    container_name: mvp-project
    restart: always
    ports:
      - "8904:80"
    volumes:
      - .:/var/www/html

    mem_limit: 1024MB
    networks:
      - mongodb-network
    environment:
      - PHP_ERROR_REPORTING='E_ALL & ~E_STRICT'

networks:
  mongodb-network:
    external: true
